targets:
  ubuntu-14.04:
    after:
      - cp /opt/clawiod/config.core.json /etc/clawiod/config.core.json
      - cp /opt/clawiod/config.fileauth.json /etc/clawiod/clawio.d/config.fileauth.json
      - sudo su clawiod mkdir -p /home/clawiod/data/notmp
      - sudo su clawiod mkdir -p /home/clawiod/data/tmp
  ubuntu-12.04:
  centos-6:
  centos-7:
  debian-7:
  debian-8:
  fedora-20:
  sles-12:

user: clawiod
group: clawiod

cli: clawiod


