targets:
  ubuntu-14.04:
    after_install: ./packager/debian/postinst
  ubuntu-12.04:
    after_install: ./packager/debian/postinst
  centos-6:
  centos-7:
  debian-7:
    after_install: ./packager/debian/postinst
  debian-8:
    after_install: ./packager/debian/postinst
  fedora-20:
  sles-12:

user: clawiod
group: clawiod

cli: clawiod


