language: go
go:
- 1.6
- tip
script:
- go get ./...
- go test ./...
- go list -f '{{if gt (len .TestGoFiles) 0}}"go test -coverprofile {{.Name}}.coverprofile
  -coverpkg ./... {{.ImportPath}}"{{end}}' ./... | xargs -I {} bash -c {}
- go get github.com/wadey/gocovmerge
- gocovmerge `ls *.coverprofile` > coverage.txt
- bash <(curl -s https://codecov.io/bash) -f coverage.txt
- "./build.sh"
deploy:
  provider: releases
  file:
    - "releases/clawiod-darwin-amd64"
    - "releases/clawiod-windows-amd64"
    - "releases/clawiod-linux-amd64"
  on:
    repo: clawio/clawiod
  api_key:
    secure: yt2X1aQg4CCx75udZZsMJZ2dfkgPdI3ywY6FPeR+KrvnMWarDP8LqaZyOabbQf1doZUss+Kr/icEyl1YQF307sdKVa6exuEkmdpkaVfmEgu3mxsdasQi5nQuo7JZ79J+rrYIvkmz8BUwlPXM9kbVWr9SeO2RAf7kFotqA+qzAPoMk3ruCPDq5RxaJKwjYuKXZq6agHbgF/FoBDFEqoxqMsynxtxwC4mrcT+PABIOBybnu1XA4HzBehAyb2XfyxzbByXrXjxpU5fXluW9zcEx99j3OrZV3bgA/GALDEjHaT24Qt/I+Wg/VOMZ7HQ2YcPpXf80aTq7LWpG8n/7uu37sv023a1jiQoPmHokse39TFaj5SmVBrAxMRhqImBA/kg2H8cGsRT8WUXinxUdrwJ6aI0eouk4tOjU8lBZ7QuvTTETKTk3/dq2OlSBH3S/yGRMKxyLdoBIB6i+slSj0PGXvxWhPZo7VAjdabG+86eCnYrALJZiPeXA3flX4PsflwnZ6Z3GVW7k3SA2pboCTDh1ivg+yUz85Zsgg8wAU6cw4qbR9jOWXv8w1G1/GKijE8Euzz6Y4FdpwWplf1Y+jbkMn9cD8dxPXp5j9inGRPR/ACAT97Y42xQds0ESIP2vQyNrODLudOhQqQ15ba+57ygLfA+et3BrulwoMzWnYGx38YU=
