codecov:
  branch: new
comment:
  layout: header, changes, diff
coverage:
  ignore:
  - entities.go
  - config/mock/*
  - services/authentication/authenticationcontroller/mock/*
  - services/data/datacontroller/mock/*
  - services/metadata/metadatacontroller/mock/*
  status: {}
