#!/bin/sh

set -e

cp /opt/clawiod/config/clawiod.conf /etc/clawiod/clawiod.conf
cp /opt/clawiod/config/fileauth.conf /etc/clawiod/conf.d/fileauth.conf
cp /opt/clawiod/init/sysvinit-debian/clawiod /etc/init.d/clawiod
cp /opt/clawiod/init/upstart/clawiod.conf /etc/init/clawiod.conf
mkdir -p /home/clawiod/data/tmp
mkdir -p /home/clawiod/data/notmp
chown -R clawiod:clawiod /home/clawiod
chown -R clawiod:clawiod /etc/clawiod
chmod -R 775 /home/clawiod/data
