#!/bin/sh

set -e

sudo cp /opt/clawiod/config/clawiod.conf /etc/clawiod/clawiod.conf
sudo cp /opt/clawiod/config/fileauth.conf /etc/clawiod/conf.d/fileauth.conf
sudo mkdir -p /home/clawiod/data/tmp
sudo mkdir -p /home/clawiod/data/notmp
sudo chown -R clawiod:clawiod /home/clawiod
sudo chown -R clawiod:clawiod /etc/clawiod
