// Code generated by protoc-gen-go.
// source: account.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	account.proto
	error.proto
	metadata.proto
	security.proto
	user.proto

It has these top-level messages:
	AuthenticateRequest
	AuthenticateResponse
	WhoamiRequest
	WhoamiResponse
	Error
	MkdirRequest
	MkdirResponse
	CopyRequest
	CopyResponse
	MoveRequest
	MoveResponse
	RemoveRequest
	RemoveResponse
	StatRequest
	StatResponse
	MetaDataInfo
	SecEntity
	SecCredentials
	User
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthenticateRequest struct {
	SecCredentials *SecCredentials `protobuf:"bytes,1,opt,name=sec_credentials" json:"sec_credentials,omitempty"`
}

func (m *AuthenticateRequest) Reset()                    { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string            { return proto1.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()               {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthenticateRequest) GetSecCredentials() *SecCredentials {
	if m != nil {
		return m.SecCredentials
	}
	return nil
}

type AuthenticateResponse struct {
	Ticket string `protobuf:"bytes,1,opt,name=ticket" json:"ticket,omitempty"`
	Error  *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *AuthenticateResponse) Reset()                    { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string            { return proto1.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()               {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthenticateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type WhoamiRequest struct {
	Ticket string `protobuf:"bytes,1,opt,name=ticket" json:"ticket,omitempty"`
}

func (m *WhoamiRequest) Reset()                    { *m = WhoamiRequest{} }
func (m *WhoamiRequest) String() string            { return proto1.CompactTextString(m) }
func (*WhoamiRequest) ProtoMessage()               {}
func (*WhoamiRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type WhoamiResponse struct {
	User  *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Error *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *WhoamiResponse) Reset()                    { *m = WhoamiResponse{} }
func (m *WhoamiResponse) String() string            { return proto1.CompactTextString(m) }
func (*WhoamiResponse) ProtoMessage()               {}
func (*WhoamiResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WhoamiResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *WhoamiResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto1.RegisterType((*AuthenticateRequest)(nil), "proto.AuthenticateRequest")
	proto1.RegisterType((*AuthenticateResponse)(nil), "proto.AuthenticateResponse")
	proto1.RegisterType((*WhoamiRequest)(nil), "proto.WhoamiRequest")
	proto1.RegisterType((*WhoamiResponse)(nil), "proto.WhoamiResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Account service

type AccountClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*WhoamiResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := grpc.Invoke(ctx, "/proto.Account/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*WhoamiResponse, error) {
	out := new(WhoamiResponse)
	err := grpc.Invoke(ctx, "/proto.Account/Whoami", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	Whoami(context.Context, *WhoamiRequest) (*WhoamiResponse, error)
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Account/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Whoami_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoamiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Whoami(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Account/Whoami",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Whoami(ctx, req.(*WhoamiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _Account_Authenticate_Handler,
		},
		{
			MethodName: "Whoami",
			Handler:    _Account_Whoami_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0xd8, 0x88, 0x93, 0x36, 0xc2, 0xda, 0x42, 0xdd, 0x1e, 0x94, 0x9c, 0x3c, 0xe5,
	0x50, 0xf1, 0x07, 0x94, 0x52, 0xf4, 0xac, 0x88, 0x47, 0x89, 0xeb, 0x40, 0x17, 0x35, 0x5b, 0x77,
	0x66, 0x0f, 0xfe, 0x04, 0xff, 0xb5, 0x64, 0x77, 0x8a, 0xb6, 0x84, 0x9e, 0x42, 0xde, 0x9b, 0xf7,
	0xf6, 0x9b, 0x81, 0x51, 0x63, 0x8c, 0x0b, 0x2d, 0xd7, 0x1b, 0xef, 0xd8, 0xa9, 0x41, 0xfc, 0xe8,
	0x02, 0xbd, 0x77, 0x3e, 0x69, 0xba, 0x24, 0x34, 0xc1, 0x5b, 0xfe, 0x96, 0x7f, 0x08, 0x84, 0xe2,
	0x55, 0x2b, 0x38, 0x5f, 0x04, 0x5e, 0x63, 0xcb, 0xd6, 0x34, 0x8c, 0x0f, 0xf8, 0x15, 0x90, 0x58,
	0xd5, 0x70, 0x46, 0x68, 0x5e, 0x8c, 0xc7, 0xb7, 0xce, 0x6a, 0x3e, 0x68, 0x9a, 0x5d, 0x65, 0xd7,
	0xc5, 0x7c, 0x92, 0x72, 0xf5, 0x23, 0x9a, 0xe5, 0x9f, 0x59, 0x2d, 0x61, 0xbc, 0x5b, 0x43, 0x1b,
	0xd7, 0x12, 0xaa, 0x12, 0x72, 0xb6, 0xe6, 0x1d, 0x39, 0xc6, 0x4f, 0xd5, 0x0c, 0x06, 0x91, 0x6c,
	0x7a, 0x14, 0xdb, 0x86, 0xd2, 0xb6, 0xea, 0xb4, 0xea, 0x12, 0x46, 0xcf, 0x6b, 0xd7, 0x7c, 0xda,
	0x2d, 0xc5, 0x5e, 0xba, 0xba, 0x87, 0x72, 0x3b, 0x20, 0xfd, 0x17, 0x70, 0xdc, 0x2d, 0x23, 0x70,
	0x85, 0xd4, 0x3d, 0x11, 0xfa, 0x83, 0x4f, 0xcd, 0x7f, 0x32, 0x38, 0x59, 0xa4, 0xc3, 0xa9, 0x3b,
	0x18, 0xfe, 0x67, 0x57, 0x5a, 0x26, 0x7b, 0xee, 0xa2, 0x67, 0xbd, 0x9e, 0xc0, 0xdc, 0x42, 0x9e,
	0xf0, 0xd4, 0x58, 0xc6, 0x76, 0xd6, 0xd1, 0x93, 0x3d, 0x35, 0xc5, 0x5e, 0xf3, 0xa8, 0xde, 0xfc,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x4c, 0xce, 0x9a, 0xca, 0x01, 0x00, 0x00,
}
