name: aerospike-client-go
dir: src/github.com/aerospike/aerospike-client-go

container:
  - base:
      - 192.168.106.181/build/aerospike-client-go:golang-1.3
      - 192.168.106.181/build/aerospike-client-go:golang-1.4
      - 192.168.106.181/build/aerospike-client-go:golang-1.5

build:
  - name: build
    script:
      - go get -v github.com/aerospike/aerospike-client-go
      - go build -v -x github.com/aerospike/aerospike-client-go
      - go install -v -x github.com/aerospike/aerospike-client-go/tools/cli
      - go install -v -x github.com/aerospike/aerospike-client-go/tools/benchmark
      - go install -v -x github.com/aerospike/aerospike-client-go/tools/asinfo
