// Code generated by protoc-gen-go.
// source: meta/meta.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	meta/meta.proto
	tokens/token.proto
	users/users.proto

It has these top-level messages:
	CreateFolderReq
	CreateFolderRes
	CopyReq
	CopyRes
	MoveReq
	MoveRes
	RemoveReq
	RemoveRes
	GetMetaReq
	Metadata
	CreateRequest
	CreateResponse
	GetCurrentAccountReq
	GetCurrentAccountRes
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateFolderReq struct {
	Path   string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Opaque string `protobuf:"bytes,2,opt,name=opaque" json:"opaque,omitempty"`
}

func (m *CreateFolderReq) Reset()                    { *m = CreateFolderReq{} }
func (m *CreateFolderReq) String() string            { return proto1.CompactTextString(m) }
func (*CreateFolderReq) ProtoMessage()               {}
func (*CreateFolderReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateFolderRes struct {
	Opaque string `protobuf:"bytes,1,opt,name=opaque" json:"opaque,omitempty"`
}

func (m *CreateFolderRes) Reset()                    { *m = CreateFolderRes{} }
func (m *CreateFolderRes) String() string            { return proto1.CompactTextString(m) }
func (*CreateFolderRes) ProtoMessage()               {}
func (*CreateFolderRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CopyReq struct {
	FromPath string `protobuf:"bytes,1,opt,name=from_path,json=fromPath" json:"from_path,omitempty"`
	ToPath   string `protobuf:"bytes,2,opt,name=to_path,json=toPath" json:"to_path,omitempty"`
	Opaque   string `protobuf:"bytes,3,opt,name=opaque" json:"opaque,omitempty"`
}

func (m *CopyReq) Reset()                    { *m = CopyReq{} }
func (m *CopyReq) String() string            { return proto1.CompactTextString(m) }
func (*CopyReq) ProtoMessage()               {}
func (*CopyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CopyRes struct {
	Opaque string `protobuf:"bytes,1,opt,name=opaque" json:"opaque,omitempty"`
}

func (m *CopyRes) Reset()                    { *m = CopyRes{} }
func (m *CopyRes) String() string            { return proto1.CompactTextString(m) }
func (*CopyRes) ProtoMessage()               {}
func (*CopyRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type MoveReq struct {
	FromPath string `protobuf:"bytes,1,opt,name=from_path,json=fromPath" json:"from_path,omitempty"`
	ToPath   string `protobuf:"bytes,2,opt,name=to_path,json=toPath" json:"to_path,omitempty"`
	Opaque   string `protobuf:"bytes,3,opt,name=opaque" json:"opaque,omitempty"`
}

func (m *MoveReq) Reset()                    { *m = MoveReq{} }
func (m *MoveReq) String() string            { return proto1.CompactTextString(m) }
func (*MoveReq) ProtoMessage()               {}
func (*MoveReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type MoveRes struct {
	Opaque string `protobuf:"bytes,1,opt,name=opaque" json:"opaque,omitempty"`
}

func (m *MoveRes) Reset()                    { *m = MoveRes{} }
func (m *MoveRes) String() string            { return proto1.CompactTextString(m) }
func (*MoveRes) ProtoMessage()               {}
func (*MoveRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type RemoveReq struct {
	Path   string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Opaque string `protobuf:"bytes,2,opt,name=opaque" json:"opaque,omitempty"`
}

func (m *RemoveReq) Reset()                    { *m = RemoveReq{} }
func (m *RemoveReq) String() string            { return proto1.CompactTextString(m) }
func (*RemoveReq) ProtoMessage()               {}
func (*RemoveReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type RemoveRes struct {
	Opaque string `protobuf:"bytes,1,opt,name=opaque" json:"opaque,omitempty"`
}

func (m *RemoveRes) Reset()                    { *m = RemoveRes{} }
func (m *RemoveRes) String() string            { return proto1.CompactTextString(m) }
func (*RemoveRes) ProtoMessage()               {}
func (*RemoveRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GetMetaReq struct {
	Path     string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Children bool   `protobuf:"varint,2,opt,name=children" json:"children,omitempty"`
	Opaque   string `protobuf:"bytes,3,opt,name=opaque" json:"opaque,omitempty"`
}

func (m *GetMetaReq) Reset()                    { *m = GetMetaReq{} }
func (m *GetMetaReq) String() string            { return proto1.CompactTextString(m) }
func (*GetMetaReq) ProtoMessage()               {}
func (*GetMetaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Metadata struct {
	Id                 int64       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Path               string      `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	IsFolder           bool        `protobuf:"varint,3,opt,name=is_folder,json=isFolder" json:"is_folder,omitempty"`
	Size               int64       `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	ClientModification int64       `protobuf:"varint,5,opt,name=client_modification,json=clientModification" json:"client_modification,omitempty"`
	ServerModification string      `protobuf:"bytes,6,opt,name=server_modification,json=serverModification" json:"server_modification,omitempty"`
	Xs                 string      `protobuf:"bytes,7,opt,name=xs" json:"xs,omitempty"`
	Etag               string      `protobuf:"bytes,8,opt,name=etag" json:"etag,omitempty"`
	Permissions        int64       `protobuf:"varint,9,opt,name=permissions" json:"permissions,omitempty"`
	Children           []*Metadata `protobuf:"bytes,10,rep,name=children" json:"children,omitempty"`
	Opaque             string      `protobuf:"bytes,11,opt,name=opaque" json:"opaque,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto1.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Metadata) GetChildren() []*Metadata {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto1.RegisterType((*CreateFolderReq)(nil), "proto.CreateFolderReq")
	proto1.RegisterType((*CreateFolderRes)(nil), "proto.CreateFolderRes")
	proto1.RegisterType((*CopyReq)(nil), "proto.CopyReq")
	proto1.RegisterType((*CopyRes)(nil), "proto.CopyRes")
	proto1.RegisterType((*MoveReq)(nil), "proto.MoveReq")
	proto1.RegisterType((*MoveRes)(nil), "proto.MoveRes")
	proto1.RegisterType((*RemoveReq)(nil), "proto.RemoveReq")
	proto1.RegisterType((*RemoveRes)(nil), "proto.RemoveRes")
	proto1.RegisterType((*GetMetaReq)(nil), "proto.GetMetaReq")
	proto1.RegisterType((*Metadata)(nil), "proto.Metadata")
}

func init() { proto1.RegisterFile("meta/meta.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x55, 0x9c, 0x34, 0xb6, 0x27, 0x28, 0x81, 0x41, 0x2a, 0x96, 0x7b, 0x09, 0x45, 0x42, 0x45,
	0x40, 0x2b, 0x95, 0x03, 0x27, 0xb8, 0x54, 0x82, 0x53, 0xa4, 0xca, 0x42, 0xe2, 0x18, 0x2d, 0xf1,
	0x84, 0xae, 0x14, 0x7b, 0xdd, 0xdd, 0xa5, 0x2a, 0xfc, 0x46, 0xfe, 0x0d, 0x7f, 0x00, 0xed, 0x47,
	0xdc, 0xb5, 0x55, 0x23, 0x71, 0xe8, 0x25, 0xd9, 0x99, 0x37, 0xf3, 0xde, 0x78, 0xf4, 0x06, 0x16,
	0x15, 0x69, 0x76, 0x66, 0x7e, 0x4e, 0x1b, 0x29, 0xb4, 0xc0, 0x03, 0xfb, 0x77, 0xfc, 0x01, 0x16,
	0x17, 0x92, 0x98, 0xa6, 0x4f, 0x62, 0x57, 0x92, 0x2c, 0xe8, 0x1a, 0x11, 0x26, 0x0d, 0xd3, 0x57,
	0xd9, 0x68, 0x39, 0x3a, 0x49, 0x0b, 0xfb, 0xc6, 0x43, 0x98, 0x8a, 0x86, 0x5d, 0xff, 0xa0, 0x2c,
	0xb2, 0x59, 0x1f, 0x1d, 0xbf, 0xea, 0xb7, 0xab, 0xa0, 0x74, 0xd4, 0x29, 0xfd, 0x0a, 0xf1, 0x85,
	0x68, 0x7e, 0x1a, 0x85, 0x23, 0x48, 0xb7, 0x52, 0x54, 0xeb, 0x40, 0x26, 0x31, 0x89, 0x4b, 0x23,
	0xf5, 0x0c, 0x62, 0x2d, 0x1c, 0xe4, 0xb5, 0xb4, 0xb8, 0xec, 0xce, 0x30, 0xee, 0x10, 0x3f, 0xdf,
	0x13, 0xff, 0x53, 0x7b, 0x25, 0x6e, 0xe8, 0x41, 0xb4, 0x1d, 0xf1, 0xb0, 0xf6, 0x7b, 0x48, 0x0b,
	0xaa, 0xbc, 0xfa, 0xff, 0xec, 0xf6, 0xc5, 0x5d, 0xe3, 0x30, 0xfb, 0x17, 0x80, 0xcf, 0xa4, 0x57,
	0xa4, 0xd9, 0x10, 0x7d, 0x0e, 0xc9, 0xe6, 0x8a, 0xef, 0x4a, 0x49, 0xb5, 0x15, 0x48, 0x8a, 0x36,
	0x1e, 0xfc, 0xac, 0xdf, 0x11, 0x24, 0x86, 0xb3, 0x64, 0x9a, 0xe1, 0x1c, 0x22, 0x5e, 0x5a, 0xca,
	0x71, 0x11, 0xf1, 0xb2, 0x15, 0x89, 0x02, 0x91, 0x23, 0x48, 0xb9, 0x5a, 0x6f, 0xad, 0x09, 0x2c,
	0x57, 0x52, 0x24, 0x5c, 0x39, 0x53, 0x98, 0x06, 0xc5, 0x7f, 0x51, 0x36, 0xb1, 0x14, 0xf6, 0x8d,
	0x67, 0xf0, 0x74, 0xb3, 0xe3, 0x54, 0xeb, 0x75, 0x25, 0x4a, 0xbe, 0xe5, 0x1b, 0xa6, 0xb9, 0xa8,
	0xb3, 0x03, 0x5b, 0x82, 0x0e, 0x5a, 0x05, 0x88, 0x69, 0x50, 0x24, 0x6f, 0x48, 0x76, 0x1b, 0xa6,
	0x76, 0x08, 0x74, 0x50, 0xa7, 0x61, 0x0e, 0xd1, 0xad, 0xca, 0x62, 0x8b, 0x47, 0xb7, 0xca, 0x4c,
	0x41, 0x9a, 0x7d, 0xcf, 0x12, 0x37, 0xb6, 0x79, 0xe3, 0x12, 0x66, 0x0d, 0xc9, 0x8a, 0x2b, 0xc5,
	0x45, 0xad, 0xb2, 0xd4, 0xaa, 0x87, 0x29, 0x7c, 0x1d, 0x6c, 0x0f, 0x96, 0xe3, 0x93, 0xd9, 0xf9,
	0xc2, 0x1d, 0xd0, 0xe9, 0x7e, 0x3f, 0xf7, 0xae, 0x73, 0x16, 0xae, 0xf3, 0xfc, 0xcf, 0x08, 0x26,
	0xa6, 0x1c, 0x3f, 0xc2, 0xa3, 0xf0, 0x5c, 0xf0, 0xd0, 0x73, 0xf5, 0x4e, 0x30, 0xbf, 0x3f, 0xaf,
	0xf0, 0x25, 0x4c, 0x8c, 0xd5, 0x71, 0xbe, 0xc7, 0xdd, 0x41, 0xe5, 0xdd, 0xd8, 0xd6, 0x19, 0x5b,
	0xb6, 0x75, 0xde, 0xfc, 0x79, 0x37, 0x56, 0xf8, 0x06, 0xa6, 0xce, 0x62, 0xf8, 0xd8, 0x23, 0xad,
	0x55, 0xf3, 0x7e, 0x46, 0xe1, 0x5b, 0x88, 0xbd, 0xd7, 0xf0, 0x89, 0x07, 0xef, 0xbc, 0x97, 0xf7,
	0xf7, 0xf2, 0x6d, 0x6a, 0xe3, 0x77, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x40, 0x6e, 0xac, 0x77,
	0x7b, 0x04, 0x00, 0x00,
}
